//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : Const.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//

package com.lxl.travel.utils;

import android.net.Uri;

public class Const {

	public static final String GLOB_URL = "http://114.215.115.211:8080/ETGServers/";
	// public static final String GLOB_URL =
	// "http://192.168.103.4:8080/ETGServers/";
	
	public static final String AIRPLANE = "飞机";
	public static final String TRAIN = "火车";
	public static final String BUS = "客车";
	
	public static final String ACTION_LOGIN = "com.lxl.etg.login";
	public static final String ACTION_REGISTER = "com.lxl.etg.register";
	public static final String ACTION_RESULT_NEARBY_CULINARY = "com.lxl.etg.result.nearby.culinary";
	public static final String ACTION_RESULT_NEARBY_WIFI = "com.lxl.etg.result.nearby.wifi";
	public static final String ACTION_RESULT_NEARBY_PARKING = "com.lxl.etg.result.nearby.parking";
	
	
	public static final String KEY_DATA = "data";
	public static final int CONNECTION_OUT_TIME = 200;

	public static final int STATUS_REGISTER_SUCCESS = 0;
	public static final int STATUS_REGISTER_FAIL = 101;

	public static final int STATUS_LOGIN_SUCCESS = 0;
	public static final int STATUS_LOGIN_FAIL = 101;
	
	public static final int STATUS_OK = 0;
	public static final int STATUS_ERR = 300;
	
	
	public static final int RESULT_PICK_PHOTO_NORMAL = 500;

	/** 传递fregment集合用的参数 */
	public static final String FRAGMENTS = "list of fragment";

	public static final String HOME_PAGE_ACTIVITY = "HomePageActivity";

	/** 天气数据广播常量 */
	public static final String WEATHER_DATA_STATUSCODE = "Weather_Datas_tatusCode";
	public static final String WEATHER_DATA_RESPONSESTRING = "Weather_Datas_responseString";
	public static final String WEATHER_DATA_THROWABLE = "Weather_Datas_throwable";
	// public static final String WEATHER_DATA_REQUEST_FINISHED =
	// "Weather_Datas_throwable_request_finished";
	public static final int WEATHER_DATA_REQUEST_SUCCESSED = 200;
	public static final int WEATHER_DATA_REQUEST_FINISH = -200;

	/** 天气数据广播接收器的action */
	public static final String RECEIVE_WEATHER_DATA = "WEATHER_DATA_RECEIVER";
	/** 请求paln接收数据的广播action */
	public static final String ACTION_RESPONE_PLAN = "com.lxl.travel.fragment.plan";
	/** plan数据广播常量 */
	public static final int STATUS_RECEIVE_OK = 200;
	public static final int STATUS_RECEIVE_FAILED = -200;
	public static final int STATUS_RECEIVED_DATA_PARSE_FAILED = -201;
	public static final int STATUS_SERVER_CONNECT_FAILED = -202;	
	
	/**addPlan常量*/
	public static final String RECEIVE_ADD_PLAN_RESPONSE = "RECEIVE_ADD_PLAN_RESPONSE";//接收添加计划之后,发送的返回信息的广播接收器action
	
	/**历史计划页面加载数据广播接收器*/
	public static final String RECEIVE_PAST_PLAN = "RECEIVE_PAST_PLAN";
	public static final String PAST_PLAN_DATA = "PAST_PLAN_DATA";
	
	public static final String ACTION_LOCATION_CHANGED = "com.lxl.travel.locationChanged";
	/**选择图片的请求码*/
	public static final int CROP_A_PICTURE = 501;
	
	public static final int CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE = 502;
	
}
