//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : RegisterIntentService.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//


package com.lxl.travel.biz;

import org.json.JSONObject;

import android.app.IntentService;
import android.content.Intent;

import com.lidroid.xutils.HttpUtils;
import com.lidroid.xutils.exception.HttpException;
import com.lidroid.xutils.http.RequestParams;
import com.lidroid.xutils.http.ResponseInfo;
import com.lidroid.xutils.http.callback.RequestCallBack;
import com.lidroid.xutils.http.client.HttpRequest.HttpMethod;
import com.lxl.travel.entity.UserEntity;
import com.lxl.travel.utils.Const;
import com.lxl.travel.utils.ExceptionUtil;
import com.lxl.travel.utils.LogUtil;



public class RegisterIntentService extends IntentService{

	public RegisterIntentService() {
		super("RegisterIntentService");
		// TODO Auto-generated constructor stub
	}

	@Override
	protected void onHandleIntent(Intent intent) {
		HttpUtils httpUtils = new HttpUtils(10000);
		UserEntity entity = (UserEntity) intent.getSerializableExtra(Const.KEY_DATA);
		String url = Const.GLOB_URL + "regiest";
		LogUtil.i("TAG", "url = " + url);
		RequestParams params = new RequestParams();
		params.addBodyParameter("gender", entity.getGender());
		params.addBodyParameter("md5password", entity.getMd5password());
		params.addBodyParameter("nickname", entity.getNickname());
		params.addBodyParameter("username", entity.getUsername());
		params.addBodyParameter("lastLoginTime", ""+entity.getLastLoginTime());
		params.addBodyParameter("regTime", ""+entity.getRegTime());
		httpUtils.send(HttpMethod.POST, url, params,new RequestCallBack<String>() {
			int status;
			@Override
			public void onFailure(HttpException arg0, String arg1) {
				Intent i = new Intent(Const.ACTION_REGISTER);
				status = Const.CONNECTION_OUT_TIME;
				i.putExtra(Const.KEY_DATA, status);
				LogUtil.i("TAG", "arg0 = " + arg0.getExceptionCode());
				LogUtil.i("TAG", "arg1 = " + arg1);
				sendBroadcast(i);
			}

			@Override
			public void onSuccess(ResponseInfo<String> responseInfo) {
				String json = responseInfo.result;
				String msg = "";
				try {
					
					JSONObject object = new JSONObject(json);
					String result = object.getString("result");
					if (result.equals("ok")){
						//ע��ɹ�
						status = Const.STATUS_REGISTER_SUCCESS;
					}else if (result.equals("err")){
						//ע��ʧ��
						status = Const.STATUS_REGISTER_FAIL;
						msg = object.getString("data");
					}
				} catch (Exception e) {
					ExceptionUtil.handleException(e);
				}finally{
					Intent i = new Intent(Const.ACTION_REGISTER);
					i.putExtra(Const.KEY_DATA, status);
					i.putExtra("msg", msg);
					sendBroadcast(i);
				}
			}
		});
	}
}
