//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : AltradionsEntity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//



package com.lxl.travel.entity;

import java.io.Serializable;


public class AltradionsEntity implements Serializable{
	private String TravelName;
	private String TravelPrice;
	private String TravelStar;
	private String TravelID; //景点编号
	private String CommentGrade; //分数
	private String ProductManagerRecommand;//产品经理推荐
	private String TravelAddress;//地址
	private String Image;// 图片网址
	
	public String getTravelAddress() {
		return TravelAddress;
	}
	public void setTravelAddress(String travelAddress) {
		TravelAddress = travelAddress;
	}
	public String getTravelID() {
		return TravelID;
	}
	public void setTravelID(String travelID) {
		TravelID = travelID;
	}
	public String getTravelName() {
		return TravelName;
	}
	public void setTravelName(String travelName) {
		TravelName = travelName;
	}
	public String getTravelPrice() {
		return TravelPrice;
	}
	public void setTravelPrice(String travelPrice) {
		TravelPrice = travelPrice;
	}
	public String getTravelStar() {
		return TravelStar;
	}
	public void setTravelStar(String travelStar) {
		TravelStar = travelStar;
	}
	public String getCommentGrade() {
		return CommentGrade;
	}
	public void setCommentGrade(String commentGrade) {
		CommentGrade = commentGrade;
	}
	public String getProductManagerRecommand() {
		return ProductManagerRecommand;
	}
	public void setProductManagerRecommand(String productManagerRecommand) {
		ProductManagerRecommand = productManagerRecommand;
	}
	public String getImage() {
		return Image;
	}
	public void setImage(String image) {
		Image = image;
	}
	/*@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((CommentGrade == null) ? 0 : CommentGrade.hashCode());
		result = prime * result + ((Image == null) ? 0 : Image.hashCode());
		result = prime
				* result
				+ ((ProductManagerRecommand == null) ? 0
						: ProductManagerRecommand.hashCode());
		result = prime * result
				+ ((TravelAddress == null) ? 0 : TravelAddress.hashCode());
		result = prime * result
				+ ((TravelID == null) ? 0 : TravelID.hashCode());
		result = prime * result
				+ ((TravelName == null) ? 0 : TravelName.hashCode());
		result = prime * result
				+ ((TravelPrice == null) ? 0 : TravelPrice.hashCode());
		result = prime * result
				+ ((TravelStar == null) ? 0 : TravelStar.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AltradionsEntity other = (AltradionsEntity) obj;
		if (CommentGrade == null) {
			if (other.CommentGrade != null)
				return false;
		} else if (!CommentGrade.equals(other.CommentGrade))
			return false;
		if (Image == null) {
			if (other.Image != null)
				return false;
		} else if (!Image.equals(other.Image))
			return false;
		if (ProductManagerRecommand == null) {
			if (other.ProductManagerRecommand != null)
				return false;
		} else if (!ProductManagerRecommand
				.equals(other.ProductManagerRecommand))
			return false;
		if (TravelAddress == null) {
			if (other.TravelAddress != null)
				return false;
		} else if (!TravelAddress.equals(other.TravelAddress))
			return false;
		if (TravelID == null) {
			if (other.TravelID != null)
				return false;
		} else if (!TravelID.equals(other.TravelID))
			return false;
		if (TravelName == null) {
			if (other.TravelName != null)
				return false;
		} else if (!TravelName.equals(other.TravelName))
			return false;
		if (TravelPrice == null) {
			if (other.TravelPrice != null)
				return false;
		} else if (!TravelPrice.equals(other.TravelPrice))
			return false;
		if (TravelStar == null) {
			if (other.TravelStar != null)
				return false;
		} else if (!TravelStar.equals(other.TravelStar))
			return false;
		return true;
	}*/
	@Override
	public String toString() {
		return "AltradionsEntity [TravelName=" + TravelName + ", TravelPrice="
				+ TravelPrice + ", TravelStar=" + TravelStar + ", TravelID="
				+ TravelID + ", CommentGrade=" + CommentGrade
				+ ", ProductManagerRecommand=" + ProductManagerRecommand
				+ ", TravelAddress=" + TravelAddress + ", Image=" + Image + "]";
	}

	
	
}
