//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : PlanEntity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//



package com.lxl.travel.entity;

import java.io.Serializable;
import java.sql.Date;


public class PlanEntity implements Serializable{
	private int id;
	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return id;
	}
	private String username;
	private Date fromDate;
	private Date toDate;
	private double  AltradionsPrice;
	private String AltradionsAddress;
	private String remark;
	
	
	public PlanEntity() {
		super();
	}
	public PlanEntity(String username, Date fromDate, Date toDate,
			double altradionsPrice, String altradionsAddress, String remark) {
		super();
		this.username = username;
		this.fromDate = fromDate;
		this.toDate = toDate;
		AltradionsPrice = altradionsPrice;
		AltradionsAddress = altradionsAddress;
		this.remark = remark;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public Date getFromDate() {
		return fromDate;
	}
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	public Date getToDate() {
		return toDate;
	}
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	public double getAltradionsPrice() {
		return AltradionsPrice;
	}
	public void setAltradionsPrice(double altradionsPrice) {
		AltradionsPrice = altradionsPrice;
	}
	public String getAltradionsAddress() {
		return AltradionsAddress;
	}
	public void setAltradionsAddress(String altradionsAddress) {
		AltradionsAddress = altradionsAddress;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
}
