//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : AltradionsEntity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//



package com.lxl.travel.entity;

import java.io.Serializable;
import java.util.ArrayList;


public class TravelDetailEntity implements Serializable{
	private String OpenTimeDesc;  //开门、关门时间
	private String Introduction;  // 返回的一段字符串（其中有图片的URL：http:*****.jpg）
	private ArrayList<String> imageList = new ArrayList<String>();
	
	public String getOpenTimeDesc() {
		return OpenTimeDesc;
	}
	public void setOpenTimeDesc(String openTimeDesc) {
		OpenTimeDesc = openTimeDesc;
	}
	public String getIntroduction() {
		return Introduction;
	}
	public void setIntroduction(String introduction) {
		Introduction = introduction;
	}
	
	public ArrayList<String> getImageList() {
		return imageList;
	}
	public void setImageList(ArrayList<String> imageList) {
		this.imageList = imageList;
	}
	@Override
	public String toString() {
		return "TravelDetailEntity [OpenTimeDesc=" + OpenTimeDesc
				+ ", Introduction=" + Introduction + ", imageList=" + imageList
				+ "]";
	}
		
	
}

	
