//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : WeatherEntity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//



package com.lxl.travel.entity;


public class WeatherEntity {
	
	/**当前天气状况*/
	private CurrentWeather currentWeather;
	
	/**明日天气状况*/
	private FurtherWeather tomorrowWeather;
	
	/**后天天气状况*/
	private FurtherWeather dayAftertomorrowWeather;
	
	/**当前查询城市*/
	private String city;
	


	public WeatherEntity(CurrentWeather currentWeather,
			FurtherWeather tomorrowWeather,
			FurtherWeather dayAftertomorrowWeather, String city) {
		super();
		this.currentWeather = currentWeather;
		this.tomorrowWeather = tomorrowWeather;
		this.dayAftertomorrowWeather = dayAftertomorrowWeather;
		this.city = city;
	}

	public WeatherEntity() {
		super();
	}
	
	
	
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public CurrentWeather getCurrentWeather() {
		return currentWeather;
	}

	public void setCurrentWeather(CurrentWeather currentWeather) {
		this.currentWeather = currentWeather;
	}

	public FurtherWeather getTomorrowWeather() {
		return tomorrowWeather;
	}

	public void setTomorrowWeather(FurtherWeather tomorrowWeather) {
		this.tomorrowWeather = tomorrowWeather;
	}

	public FurtherWeather getDayAftertomorrowWeather() {
		return dayAftertomorrowWeather;
	}

	public void setDayAftertomorrowWeather(FurtherWeather dayAftertomorrowWeather) {
		this.dayAftertomorrowWeather = dayAftertomorrowWeather;
	}

	@Override
	public String toString() {
		return "WeatherEntity [currentWeather=" + currentWeather
				+ ", tomorrowWeather=" + tomorrowWeather
				+ ", dayAftertomorrowWeather=" + dayAftertomorrowWeather
				+ ", city=" + city + "]";
	}
}
