//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : AltradionsDetialActivity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//
/**
 * @author cm
 * */

package com.lxl.travel.activity;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.util.Log;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.lidroid.xutils.BitmapUtils;
import com.lxl.travel.ETGApplication;
import com.lxl.travel.biz.CmTravelDetailBiz;
import com.lxl.travel.entity.AltradionsEntity;
import com.lxl.travel.entity.PlanEntity;
import com.lxl.travel.entity.TravelDetailEntity;
import com.lxl.travel.utils.JsonParser;
import com.lxl.trivel.R;
/** 	这个Activity为旅游界面点击item后跳转的界面，显示旅游景点的详细信息。1.点击最上方的图片可以显示图像TOAST提示
 * 2.点击加入计划可以实现计划的加入。 */ 
public class AltradionsDetialActivity extends Activity{
	
	public TextView tv01;		//textview为返回数据，imageview为返回的图片
	public TextView tv02;
	public TextView tv03;
	public ImageView iv01;
	private AltradionsEntity altradionsEntity;  //这个“实体类”负责 装 返回的景点数据。
	public ArrayList<String> list = new ArrayList<String>();  //这个list为提取json中String中，以http开头以jpg./结尾中间的网站URL
	BitmapUtils btutils ;   //Xutils中的工具类 用于缓存加载图片
	private LinearLayout ll;   //这个LL主要是为了加入imageview（上诉字符串能提取多少网站的URL就能加入多少图片）
	private View view;
	private ImageView iv;
	private Intent fileintent;
	
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.travel_detail);
		getActionBar().hide();
		altradionsEntity = (AltradionsEntity) getIntent().getSerializableExtra("TravelDetail");
		//Log.i("TravelDetail = ", altradionsEntity.toString());
		fileintent = getIntent();
		setviews();
		setlisteners();
		
	}
	public void test(String s){
		btutils = new BitmapUtils(this);
		//1.解析拿到的json 数据 将其转换为实体类
		TravelDetailEntity entity = JsonParser.parserForDetail(s);
		//2.1设置textview上的数据
		tv02.setText(entity.getOpenTimeDesc());
		tv01.setText(altradionsEntity.getTravelAddress());
		tv03.setText(altradionsEntity.getProductManagerRecommand());
		btutils.display(iv01, altradionsEntity.getImage());
		//2.2设置之前还要 将实体类的第二个变量转化为 ：数量不知的图像数据（String）放入集合（例子：src=\"http*****.jpg.\"  截取网址URL）	
		String pull = entity.getIntroduction();
		//Log.i("PULL = ", pull);
		String titel = "src=\"";
		String from = "\"";
		int Start = pull.indexOf(titel)+5;
		int end = pull.indexOf(from, Start);
		if(Start<end){
		if(Start!=4){
			Log.i("Start = ", Start+"");
			Log.i("end = ", end+"");
			String ss = (String) pull.subSequence(Start, end);
			list.add(ss);
		}
			while(Start!=-1){
				Start = pull.indexOf(titel, end)+5;
				end = pull.indexOf(from, Start);
				if(Start==4){
					break;
				}
				String sss = (String) pull.subSequence(Start, end);
				System.out.println(sss);
				list.add(sss);
			}
		
			entity.setImageList(list);
			//Log.i("imageURL[2] = ", list.get(2));
		//3.判断集合的长度，添加等量的imageview放入ScrollView中
			  ll = (LinearLayout) findViewById(R.id.LinearLayout_imageDetail);
			for (int i = 0; i < list.size(); i++) {
				  view = View.inflate(this, R.layout.linearlayout_image_detail, null);
				  iv = (ImageView) view.findViewById(R.id.imageView_detail);
				  try {
					ll.addView(view);
					btutils.display(iv, list.get(i));
				} catch (Exception e) {
					e.printStackTrace();
				}		 
			}
		}
	}
	

	private void setlisteners() {
		//暂时未用上；
	}
	//加入计划按键的监听
	public void jiaruPLAN(View v){
		if(ETGApplication.userEntity == null){
			Toast.makeText(this, "并没有登录~亲", 0).show();
			Intent intent = new Intent(AltradionsDetialActivity.this, LoginActivity.class);
			startActivity(intent);
		}else{
		Intent intent = new Intent(this,AddPlanActivity.class);
		intent.putExtra("AltradionsEntity", altradionsEntity);
		intent.putExtra("fromDate", fileintent.getStringExtra("timeFrom"));//这两个数据是   加入计划界面跳转到本界面是传的出发时间
		intent.putExtra("toDate", fileintent.getStringExtra("timeto"));//   和返回时间  （到时候点击“加入计划”按键时返回回去）
		startActivity(intent);
		finish();
		}
	}

	private void setviews() {
		iv01 = (ImageView)findViewById(R.id.AltradionsDetialActivityimageView1);
		tv01 = (TextView)findViewById(R.id.AltradionsDetialActivitytextView1);
		tv02 = (TextView)findViewById(R.id.AltradionsDetialActivitytextView2);
		tv03 = (TextView)findViewById(R.id.AltradionsDetialActivitytextView3);
		new CmTravelDetailBiz(this, Integer.parseInt(altradionsEntity.getTravelID())).GetTravelDetail();
		
	}
//第一个imageview的监听（弹出吐司）
	public void image_onClick(View view){
		MyToast my = new MyToast();
		my.myTosat(AltradionsDetialActivity.this, R.drawable.b01, "点击“加入计划”试试~", Toast.LENGTH_LONG);
	}
	//自定义吐司（图片居中，文字在旁边）
	class MyToast {
	    public   void myTosat(Context context , int imageId ,String content , int duration){
	        //new一个toast传入要显示的activity的上下文
	        Toast toast = new Toast(context);
	        //显示的时间
	        toast.setDuration(duration);
	        //显示的位置
	        toast.setGravity(Gravity.BOTTOM, 0, 300);
	        //重新给toast进行布局
	        LinearLayout toastLayout = new LinearLayout(context);
	        toastLayout.setOrientation(LinearLayout.HORIZONTAL);
	        toastLayout.setGravity(Gravity.CENTER_VERTICAL);
	       
	        ImageView imageView = new ImageView(context);
	        imageView.setImageResource(imageId);
	        imageView.setLayoutParams(new LayoutParams(200, 200));
	        //把imageView添加到toastLayout的布局当中
	        toastLayout.addView(imageView);
	       
	        TextView textView = new TextView(context);
	        textView.setText(content);
	        textView.setTextSize(30);
	        textView.setTextColor(Color.RED);
//	        textView.setBackgroundColor(Color.GRAY);
	        //把textView添加到toastLayout的布局当中
	        toastLayout.addView(textView);
	        //把toastLayout添加到toast的布局当中
	        toast.setView(toastLayout);
	        toast.show();
	    }
	}
	
	
	public void addPlan(PlanEntity planEntity) {
		
	
	}
}
