//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EasyToTravel
//  @ File Name : LoginActivity.java
//  @ Date : 2015/10/12
//  @ Author : 
//
//

package com.lxl.travel.activity;

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import android.app.ActionBar;
import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.OnTouchListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.lxl.travel.ETGApplication;
import com.lxl.travel.base.BaseActivity;
import com.lxl.travel.biz.LoginBiz;
import com.lxl.travel.entity.UserEntity;
import com.lxl.travel.utils.CameraForImageUtil;
import com.lxl.travel.utils.Const;
import com.lxl.travel.utils.ImageCompress;
import com.lxl.travel.utils.LogUtil;
import com.lxl.travel.utils.SharedPreferencesUtil;
import com.lxl.travel.utils.Tools;
import com.lxl.travel.utils.ImageCompress.CompressOptions;
import com.lxl.trivel.R;

/**��½ҳ��*/
public class LoginActivity extends BaseActivity {
	/**�û���������*/
	EditText et_login_username, et_login_password;
	/**����LoginBiz���͵Ĺ㲥������*/
	LoginBroadcastReceiver loginReceiver;
	/**���û�ע�᣿*/
	private TextView tv_login_newUser;
	/**��������?*/
	private TextView tv_login_forgetPassword;
	private ImageView iv_login_logo;
	private Button btn_login_submit;
	/**ʹ��SharedPreferencesUtilʱ��Ҫ�������ݵ�keyֵ*/
	private static String[] keys = new String[] { "username", "md5password",
			"nickname", "gender", "lastLoginTime", "regTime" };

	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_login);
		//ȥ��actionBar
		getActionBar().hide();
		setView();
		//��ȡSharedPreferencesƫ������
		setData();
		setListener();
		//ע��㲥������
		loginReceiver = new LoginBroadcastReceiver();
		IntentFilter filter = new IntentFilter();
		filter.addAction(Const.ACTION_LOGIN);
		registerReceiver(loginReceiver, filter);
	}
	@Override
	protected void onDestroy() {
		// TODO Auto-generated method stub
		//ע���㲥������
		unregisterReceiver(loginReceiver);
		super.onDestroy();
	}

	private void setView() {
		et_login_username = (EditText) findViewById(R.id.et_login_username);
		et_login_password = (EditText) findViewById(R.id.et_login_password);
		iv_login_logo = (ImageView)findViewById(R.id.iv_login_logo);
		btn_login_submit = (Button)findViewById(R.id.btn_login_submit);
		
		tv_login_newUser = (TextView) findViewById(R.id.tv_login_newUser);
		tv_login_forgetPassword = (TextView) findViewById(R.id.tv_login_forget_password);
	}
	/**��ȡƫ�������е�����*/
	private void setData() {
		/*
		 * private String username,md5password,nickname,gender; private Date
		 * lastLoginTime, regTime;
		 */
		//userInfoΪ�����û���¼��Ϣ  ���ļ���
		Map<String, String> data = SharedPreferencesUtil.getPerferences(this,
				"userInfo", keys);
		//ͨ����Ӧ��key��ȡ��Ӧ��ֵ��keys[0]Ϊ�û�����Ϣkeyֵ��data.get(keys[1])Ϊ������Ϣkeyֵ
		et_login_username.setText(data.get(keys[0]));
		et_login_password.setText(data.get(keys[1]));
		File file = CameraForImageUtil.getOutputMediaFile(data.get(keys[0]));
		if (file.exists()){
			ImageCompress.CompressOptions options = new CompressOptions();
			options.uri = Uri.fromFile(file);
			options.maxHeight = 78;
			options.maxWidth = 78;

			ImageCompress imageCompress = new ImageCompress();
			Bitmap bitmap = imageCompress.compressFromUri(
					LoginActivity.this, options);
			/* bitmap = BitmapUtil.loadBitmap(file.getAbsolutePath(), 48, 48); */
			iv_login_logo.setImageBitmap(bitmap);
		}
	}

	private void setListener() {
		//TextView ֻ������Touch�¼�
		tv_login_newUser.setOnTouchListener(new OnTouchListener() {

			@Override
			public boolean onTouch(View v, MotionEvent event) {
				//���¼�Ϊ̧��ʱ����ת��ע��ҳ��
				if (event.getAction() == MotionEvent.ACTION_UP) {
					Intent intent = new Intent(LoginActivity.this,
							RegisterAcitvity.class);
					startActivity(intent);
				}
				return true;
			}
		});
		tv_login_forgetPassword.setOnTouchListener(new OnTouchListener() {

			@Override
			public boolean onTouch(View v, MotionEvent event) {
				if (event.getAction() == MotionEvent.ACTION_UP) {
					Toast.makeText(LoginActivity.this, "�������룬������ע��",
							Toast.LENGTH_SHORT).show();
				}
				return true;
			}
		});
	}

	public void onClick(View v) {
		switch (v.getId()) {
		case R.id.btn_login_submit://��¼��ť
			// �����½
			if (checkLoginInfo()) {//����¼��Ҫ����Ϣ�Ƿ���д��ȷ
				//����ProgressDialog
				Tools.showProgressDialog(this, "����Ŭ����½��...");
				btn_login_submit.setEnabled(false);
				//���������̣߳�ִ�е�¼ҵ��
				new Thread() {
					public void run() {
						//�½���¼ҵ��
						new LoginBiz(LoginActivity.this).login(
								et_login_username.getText().toString().trim(),//�û���
								et_login_password.getText().toString().trim());//����
					};
				}.start();
			}
			break;
		}
	}
	/**����¼��Ϣ������¼��Ϣȫ����ȷ�򷵻�true�����򷵻�false*/
	private boolean checkLoginInfo() {
		//�ж��û����Ƿ�Ϊ��
		if ("".equals(et_login_username.getText().toString().trim())) {
			Toast.makeText(this, "�˺Ų���Ϊ��", Toast.LENGTH_SHORT).show();
			return false;
		}
		//�ж������Ƿ�Ϊ��
		if ("".equals(et_login_password.getText().toString().trim())) {
			Toast.makeText(this, "���벻��Ϊ��", Toast.LENGTH_SHORT).show();
			return false;
		}
		return true;
	}
	/**����LoginBiz���͵Ĺ㲥�������࣬�����յ���¼ҵ�񷵻صĹ㲥ʱ���жϵ�¼�Ƿ�ɹ�*/
	class LoginBroadcastReceiver extends BroadcastReceiver {

		@Override
		public void onReceive(Context context, Intent intent) {
			//��¼���״̬��
			int status = intent.getIntExtra(Const.KEY_DATA, -1);
			//�ر�ProgressDialog
			Tools.closeProgressDialog();
			btn_login_submit.setEnabled(true);
			switch (status) {
			case Const.CONNECTION_OUT_TIME://���ӳ�ʱ
				Toast.makeText(LoginActivity.this, "����ʱ", Toast.LENGTH_SHORT)
				.show();
				break;
			case Const.STATUS_LOGIN_SUCCESS://״̬��Ϊ��¼�ɹ�
				Toast.makeText(LoginActivity.this, "��½�ɹ�", Toast.LENGTH_SHORT)
						.show();
				//ȡ�õ�¼biz���ص�user��Ϣ
				UserEntity entity = (UserEntity) intent
						.getSerializableExtra("entity");
				// ����ϢΪ�գ���ִ�У�ֱ�ӷ���
				if (entity == null) {
					return;
				}
				//���û���Ϣ���浽Application
				ETGApplication.userEntity = entity;
				LogUtil.i("userEntity", ":" + entity);
				//���û���Ϣ���浽ƫ������
				List<String> data = new ArrayList<String>();
				// ���浽�ļ�
				// list��һ��Ҫ����˳�򴢴棬��keys����һ��
				// "username","md5password","nickname","gender","lastLoginTime",
				// "regTime"
				data.add(entity.getUsername());
				data.add(entity.getMd5password());
				data.add(entity.getNickname());
				data.add(entity.getGender());
				data.add("" + entity.getLastLoginTime());
				data.add("" + entity.getRegTime());
				SharedPreferencesUtil.saveShared(LoginActivity.this,
						"userInfo", keys, data);
				//������ҳ
				Intent i = new Intent(LoginActivity.this,
						HomePageActivity.class);
				startActivity(i);
				finish();
				break;
			case Const.STATUS_LOGIN_FAIL://״̬��Ϊ��¼ʧ��
				String msg = intent.getStringExtra("msg");//�õ���¼ʧ��ԭ�򣬲�Toast
				Toast.makeText(LoginActivity.this, msg, Toast.LENGTH_LONG)
						.show();
				break;
			case -1://Ĭ��Ϊ-1��
				Toast.makeText(LoginActivity.this, "ϵͳ����,������",
						Toast.LENGTH_LONG).show();
				break;
			}
		}

	}
}
